#!/bin/sh

if [ "\$1" = "configure" ] || [ "\$1" = "abort-upgrade" ] ; then
    update-alternatives \\
        --install /usr/bin/grails grails /usr/lib/grails/${packageName}/bin/grails ${alternativesPriority} \\
        --slave /usr/bin/startGrails startGrails /usr/lib/grails/${packageName}/bin/startGrails \\
        --slave /usr/bin/grails-debug grails-debug /usr/lib/grails/${packageName}/bin/grails-debug
fi

#DEBHELPER#
